---
apiVersion:     v1
kind:           ConfigMap

metadata:
    name:       {{ include "nombre-configmap-bbdd" . }}
    namespace:  {{ .Release.Namespace }}

data:
    nombre-bbdd:   {{ $.Values.database.config.name }}
    #nombre-bbdd2:  {{ .Values.database.config.name }}
