---
{{ if not $.Values.database.config.existingSecretName }}
apiVersion:     v1
kind:           Secret

metadata:
    name:       {{ include "nombre-secret-bbdd" . }}
    namespace:  {{ $.Release.Namespace }}

data:
    {{- with $.Values.database.config }}
    password:      {{ (default (randAscii 15) .password) | b64enc | quote }}
    rootPassword:  {{ if .rootPassword }}
                        {{- .rootPassword | b64enc | quote -}}
                   {{ else -}}
                        {{ randAscii 15 | b64enc | quote }}
                   {{- end }}
    user:          {{ (default "wordpress" .user) | b64enc | quote }}
    {{ end }}
{{ end }}
