---
# Service: MariaDB - ClusterIP
apiVersion:             v1
kind:                   Service
metadata:
    name:               {{ include "nombre-servicio-bbdd" . }}
    namespace:          {{ $.Release.Namespace }}

spec:
    type:               ClusterIP
    ports:
        - port:         3306
          targetPort:   3306
    selector:
        {{- include "database-labels" $ | nindent 8 }}
