---
# Service: MariaDB - ClusterIP
apiVersion:             v1
kind:                   Service
metadata:
    name:               mariadb-service # Este nombre... es el fqdn que se mete en el DNS

spec:
    type:               ClusterIP
    ports:
        - port:         3306
          targetPort:   3306
    selector:
        app:            mariadb
