---
# StatefulSet: MariaDB - Standalone
apiVersion:             apps/v1
kind:                   StatefulSet

metadata:
    name:               {{ include "nombre-statefulset-bbdd" . }}
    namespace:          {{ $.Release.Namespace }}

spec:
    replicas:           1
    selector:           
        matchLabels:
            {{- include "database-labels" . | nindent 12 }}

    serviceName:        {{ include "nombre-servicio-bbdd" . }} # PA QUE! Es obligatorio
                        # Para cada pod una entrada en DNS llamada: nombre_pod.mariadb-service que apuntará a la ip de ese pod
                                    # mariadb-0.mariadb-service
                                    # mariadb-1.mariadb-service
                                    # mariadb-2.mariadb-service
                        # El nombre del servicio apunta a una IP de balanceo.. pero puedo apuntar a cada pod mediante un nombre fqdn 
                        # en automático Kubernetes crea sub-servicios
    template:
        metadata:
            labels:
               {{- include "database-labels" $ | nindent 15 }}
        spec:
            containers:
                -   name:                   mariadb
                    image:                  {{ .Values.database.image.repo }}:{{ .Values.database.image.tag }}
                    imagePullPolicy:        #{{ .Values.database.image.pullPolicy }}
                        {{ if (regexMatch "^((IfNotPresent)|(Always)|(Never))$" .Values.database.image.pullPolicy ) }}
                            {{ .Values.database.image.pullPolicy }}
                        {{ else }}
                            {{ fail (printf "El valor de imagePullPolicy suministrado no es válido: '%s'. Debe ser uno de: 'Always', 'Never' o 'IfNotPresent'" .Values.database.image.pullPolicy )}}
                        {{ end }}
                    # Si me pasan un valor que no sea Always, Never o IfNotPresent
                    # Kubernetes va a dar un error MUY EXPLICITO al aplicar el fichero de manifiest:
                    # No se puede crear el StatefulSet porque el valor de imagePullPolicy no es válido
                    # Pregunta, me interesa hacer una validación en HELM? 
                    # o dado que kubernetes ya me va a controlar el error, 
                    # y va a ser explicito en él... mejor le dejo a kubernetes y me quito de follones
                    env:
                        -   name:           MARIADB_ROOT_PASSWORD
                            value:          mariadb-service
                        -   name:           MARIADB_USER
                            valueFrom:
                                secretKeyRef:
                                    name:   datos-sensibles-mariadb
                                    key:    usuario-bbdd
                        -   name:           MARIADB_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    name:   datos-sensibles-mariadb
                                    key:    password-bbdd
                        -   name:           MARIADB_DATABASE
                            valueFrom:
                                configMapKeyRef:
                                    name:   datos-mariadb
                                    key:    nombre-bbdd
                    volumeMounts:
                        -   name:           datos-persistentes-mariadb
                            mountPath:      /var/www/html
                    resources:
                        requests:
                            cpu:            500m
                            memory:         1Gi
                        limits:
                            cpu:            2
                            memory:         1Gi
    volumeClaimTemplates:
        -   metadata:
                name:   datos-persistentes-mariadb
            spec:
                resources:
                    requests: 
                        storage: 5Gi
                storageClassName: rapidito
                accessModes:
                    - ReadWriteOnce
