
# Secret datos BBDD
apiVersion:     v1
kind:           Secret

metadata:
    name:       datos-sensibles-wp

data:
    password-bbdd:      cGFzc3dvcmQ= #  echo -n "password" | base64
    root-password-bbdd: cGFzc3dvcmQ=
    usuario-bbdd:       dXN1YXJpbw==
---
# ConfigMap datos BBDD
apiVersion:     v1
kind:           ConfigMap

metadata:
    name:       datos-wp

data:
    nombre-bbdd:    mi-bbdd-wp
---
# PVC WP
apiVersion: v1
kind:       PersistentVolumeClaim
metadata:
    name:   pvc-wp
spec:
    resources:
        requests: 
            storage: 5Gi
    storageClassName: rapidito
    accessModes:
        - ReadWriteOnce
---
# Deployment: WP (apache+php), pero este no... quiero entre 2 y 5 en base al uso de CPU
apiVersion:             apps/v1
kind:                   Deployment

metadata:
    name:               wp

spec:
    replicas:           1
    selector:           
        matchLabels:
            app:        wp
    template:
        metadata:
            labels:
               app:     wp
        spec:
            containers:
                -   name:                   wp
                    image:                  wordpress:6.4 # con apache incorporado
                    imagePullPolicy:        IfNotPresent
                    env:
                        -   name:           WORDPRESS_DB_HOST
                            value:          mariadb-service
                        -   name:           WORDPRESS_DB_USER
                            valueFrom:
                                secretKeyRef:
                                    name:   datos-sensibles-wp
                                    key:    usuario-bbdd
                        -   name:           WORDPRESS_DB_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    name:   datos-sensibles-wp
                                    key:    password-bbdd
                        -   name:           WORDPRESS_DB_NAME
                            valueFrom:
                                configMapKeyRef:
                                    name:   datos-wp
                                    key:    nombre-bbdd
                    volumeMounts:
                        -   name:           datos-persistentes
                            mountPath:      /var/www/html
                    resources:
                        requests:
                            cpu:            500m
                            memory:         1Gi
                        limits:
                            cpu:            4
                            memory:         1Gi
            volumes:
                -   name:                   datos-persistentes
                    persistentVolumeClaim:
                        claimName:          pvc-wp
            
---
# StatefulSet: MariaDB - Standalone
apiVersion:             apps/v1
kind:                   StatefulSet

metadata:
    name:               mariadb

spec:
    replicas:           1
    selector:           
        matchLabels:
            app:        mariadb
    serviceName:        mariadb-service # PA QUE! Es obligatorio
                        # Para cada pod una entrada en DNS llamada: nombre_pod.mariadb-service que apuntará a la ip de ese pod
                                    # mariadb-0.mariadb-service
                                    # mariadb-1.mariadb-service
                                    # mariadb-2.mariadb-service
                        # El nombre del servicio apunta a una IP de balanceo.. pero puedo apuntar a cada pod mediante un nombre fqdn 
                        # en automático Kubernetes crea sub-servicios
    template:
        metadata:
            labels:
               app:     mariadb
        spec:
            containers:
                -   name:                   mariadb
                    image:                  mariadb:11.2
                    imagePullPolicy:        IfNotPresent
                    env:
                        -   name:           MARIADB_ROOT_PASSWORD
                            value:          mariadb-service
                        -   name:           MARIADB_USER
                            valueFrom:
                                secretKeyRef:
                                    name:   datos-sensibles-mariadb
                                    key:    usuario-bbdd
                        -   name:           MARIADB_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    name:   datos-sensibles-mariadb
                                    key:    password-bbdd
                        -   name:           MARIADB_DATABASE
                            valueFrom:
                                configMapKeyRef:
                                    name:   datos-mariadb
                                    key:    nombre-bbdd
                    volumeMounts:
                        -   name:           datos-persistentes-mariadb
                            mountPath:      /var/www/html
                    resources:
                        requests:
                            cpu:            500m
                            memory:         1Gi
                        limits:
                            cpu:            2
                            memory:         1Gi
    volumeClaimTemplates:
        -   metadata:
                name:   datos-persistentes-mariadb
            spec:
                resources:
                    requests: 
                        storage: 5Gi
                storageClassName: rapidito
                accessModes:
                    - ReadWriteOnce
        
---
# Service: MariaDB - ClusterIP
apiVersion:             v1
kind:                   Service
metadata:
    name:               mariadb-service # Este nombre... es el fqdn que se mete en el DNS

spec:
    type:               ClusterIP
    ports:
        - port:         3306
          targetPort:   3306
    selector:
        app:            mariadb
---
# Service: WP - ClusterIP | NodePort | LoadBalancer
apiVersion:             v1
kind:                   Service
metadata:
    name:               wp-service # Este nombre... es el fqdn que se mete en el DNS

spec:
    type:               NodePort
    ports:
        - port:         80
          targetPort:   80
          nodePor:      38080
    selector:
        app:            wp
---
# Ingress
apiVersion:             networking.k8s.io/v1
kind:                   Ingress
metadata:
    name:               wp-ingress # Este nombre... es el fqdn que se mete en el DNS
    annotations:
        kubernetes.io/ingress.class: nginx
spec:
    rules:
        -   host: misuperweb.miempresa.com
            http:
                paths:
                    - backend:
                        service:
                            name: wp-service
                            port:
                                number: 80
                      path: /
                      pathType: Prefix

---
# HorizontalPodAutoescaler
apiVersion:             autoscaling/v1
kind:                   HorizontalPodAutoscaler # hpa
metadata:
    name:               wp-hpa
spec:
    minReplicas:        2
    maxReplicas:        5
    
    scaleTargetRef:
        apiVersion:     apps/v1
        kind:           Deployment
        name:           wp
        
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 50