---
# Ingress
apiVersion:             networking.k8s.io/v1
kind:                   Ingress
metadata:
    name:               wp-ingress # Este nombre... es el fqdn que se mete en el DNS
    annotations:
        kubernetes.io/ingress.class: nginx
spec:
    rules:
        -   host: misuperweb.miempresa.com
            http:
                paths:
                    - backend:
                        service:
                            name: wp-service
                            port:
                                number: 80
                      path: /
                      pathType: Prefix

