---
# Service: WP - ClusterIP | NodePort | LoadBalancer
apiVersion:             v1
kind:                   Service
metadata:
    name:               wp-service # Este nombre... es el fqdn que se mete en el DNS

spec:
    type:               NodePort
    ports:
        - port:         80
          targetPort:   80
          nodePor:      38080
    selector:
        app:            wp
