---
apiVersion:         v1
kind:               Service

metadata:
    name:           mariadb-service # Este es el nombre que se añade al DNS de kubernetes
    namespace:      wp-ivan

spec:
    type:               ClusterIP # Es el tipo por defecto... si a un servicio no le pongo tipo, es de tipo ClusterIP
    ports:
        - port:         3307 # Es el puerto de la IP del servicio
          targetPort:   3306 # De los contenedores que ofrecen el servicio
    selector:
        app:            mariadb     # Pon detras de la IP del servicio en NETFILTER a todos los pods que 
                                    # tengan esta etiqueta en el ns en el que se define este servicio
