---
# Deployment: WP (apache+php), pero este no... quiero entre 2 y 5 en base al uso de CPU
apiVersion:             apps/v1
kind:                   Deployment

metadata:
    name:               {{ include "nombre-deployment-wp" . }}
    namespace:          {{ $.Release.Namespace }}

spec:
    replicas:           {{ .Values.wordpress.replicas.min }}
    selector:           
        matchLabels:
            {{- include "wp-labels" $ | nindent 12 }}
    template:
        metadata:
            labels:
                {{- include "wp-labels" $ | nindent 16 }}
        spec:
            containers:
                -   name:                   wp
                    {{- include "imagen" .Values.wordpress | nindent 20 }}
                    env:
                        -   name:           WORDPRESS_DB_HOST
                            value:          {{ include "nombre-servicio-bbdd" . }}
                        -   name:           WORDPRESS_DB_USER
                            valueFrom:
                                secretKeyRef:
                                    name:   {{ include "nombre-secreto-bbdd" . }}
                                    key:    user
                        -   name:           WORDPRESS_DB_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    name:   {{ include "nombre-secreto-bbdd" . }}
                                    key:    password
                        -   name:           WORDPRESS_DB_NAME
                            valueFrom:
                                configMapKeyRef:
                                    name:   {{ include "nombre-configmap-bbdd" . }}
                                    key:    nombre-bbdd
                        {{- include "extra-env-vars-wordpress" $.Values.wordpress | nindent 24 }}
                    volumeMounts:
                        -   name:           datos-persistentes
                            mountPath:      /var/www/html
                    {{- include "define-resources" $.Values.wordpress.resources | nindent 20 }}
            volumes:
                -   name:                   datos-persistentes
                {{- if not $.Values.wordpress.persistence.enabled }}
                    emptyDir:               {}
                {{- else }}
                    persistentVolumeClaim:
                        claimName:          {{ default (include "nombre-pvc-wp" .) .Values.wordpress.persistence.existingClaimName }}
                {{- end }}
