---
{{ if .Values.wordpress.replicas.scaling.enabled }}
# HorizontalPodAutoescaler
apiVersion:             autoscaling/v1
kind:                   HorizontalPodAutoscaler # hpa
metadata:
    name:               wp-hpa
spec:
    minReplicas:        {{ .Values.wordpress.replicas.min }}
    maxReplicas:        {{ .Values.wordpress.replicas.scaling.max }}
    
    scaleTargetRef:
        apiVersion:     apps/v1
        kind:           Deployment
        name:           {{ template "nombre-deployment-wp" . }}
        
    metrics:
      {{ .Values.wordpress.replicas.scaling.metrics }}
{{ end }}