---
# Ingress
apiVersion:             networking.k8s.io/v1
kind:                   Ingress
metadata:
    name:               {{ include "nombre-ingress" . }}
spec:
    ingressClassName:   {{ .Values.wordpress.ingress.className }}
    rules:
        -   host: {{ .Values.wordpress.ingress.host }}
            http:
                paths:
                    - backend:
                        service:
                            name: {{ template "nombre-servicio-wp" . }}
                            port:
                                number: 80
                      path: /
                      pathType: Prefix

