---
# PVC WP
{{- if .Values.wordpress.persistence.enabled }}
apiVersion: v1
kind:       PersistentVolumeClaim
metadata:
    name:   {{ include "nombre-pvc-wp" . }}
spec:
    resources:
        requests: 
            storage: {{ .Values.wordpress.persistence.capacity }}
    storageClassName: {{ .Values.wordpress.persistence.storageClass }}
    accessModes:
        - ReadWriteOnce
{{- end }}