{{- if .Values.wordpress.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "nombre-servicio-wp" . }}
  labels:
    app: {{ template "nombre-deployment-wp" . }}
spec:
  type: {{ .Values.wordpress.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
      {{ if .Values.wordpress.service.nodePort }}{{ .Values.wordpress.service.nodePort }}{{ end }}
  selector:
        {{- include "wp-labels" $ | nindent 8 }}
{{- end }}
