# Un objetivo es que alguien pueda desplegar el chart sin tocar 1 coma... y que funcione.
wordpress:
    replicas:
        min:                1
        scaling:
            enabled:        false
            max:            ~
            metrics:        []
    ingress:
        enabled:            false
        host:               ~
        ingressClassName:   ~
        extra-annotations:  {}
    service:
        type:               NodePort
        nodePort:           ~ # Se obtenga en automático
    image:
        registry:           ~
        repo:               wordpress
        tag:                6.4
        pullPolicy:         IfNotPresent
    extraLabels:           {}
    #extra-annotations:     {}
    extraEnv:              
        #WORDPRESS_DB_USER: RUINA
        WORDPRESS_DB_HOST: miServicio
        vaBien:            valor
    #extra-initContainers:  []
    #extra-containers:      []
    #affinities:            {}
    #nodeSelector:          {}
    resources:              {}
        #requests:
        #    cpu:    
        #    memory: 
        #limits:
        #    cpu:    
        #    memory: 
    persistence:
        enabled:            false
        existingClaimName:  ~ # Si este se pone, te ignoro los de abajo
        capacity:           ~    
        storageClassName:   ~

database:
    config:
        name:               wordpress
        existingSecretName: ~ # Si pones aquí algo, se ignoran los de abajo: user, password, root-password
                              # En ese caso se buscará en ese secreto las claves: user, password, root-password
        user:               wordpress
        password:           ~ # Si no me ponen password, genero uno aleatorio
        rootPassword:       ~ # Si no me ponen root-password, genero uno aleatorio
    extraLabels:           # {}
        label1:             valor1
        label2:             valor2
    image:
        registry:           ~
        repo:               mariadb
        tag:                11.2
        pullPolicy:         IfNotPresent # Always Never IfNotPresent
    extraEnv:               #{}
        #MARIADB_PASSWORD: OtroValor
        estoSI:               valor
    resources:              {}
        #requests:
        #    cpu:    3       300m
        #    memory: 23   Mi Gi Ki
        #limits:
        #    cpu:    
        #    memory: 
    persistence:
        enabled:            false
        existingClaimName:  ~ # Si este se pone, te ignoro los de abajo
        capacity:           ~    
        storageClassName:   ~
