---
apiVersion:     v1
kind:           Secret

metadata:
    name:       datos-sensibles-wp

data:
    password-bbdd:      cGFzc3dvcmQ= #  echo -n "password" | base64
    root-password-bbdd: cGFzc3dvcmQ=
    usuario-bbdd:       dXN1YXJpbw==
