---
apiVersion:         v1
kind:               Service

metadata:
    name:           wp-service # Este es el nombre que se añade al DNS de kubernetes
    namespace:      wp-ivan

spec:
    type:               NodePort # Es el tipo por defecto... si a un servicio no le pongo tipo, es de tipo ClusterIP
    ports:
        - port:         8080  # Es el puerto de la IP del servicio
          targetPort:   80    # De los contenedores que ofrecen el servicio
          nodePort:     30001 # El de los nodos.
                                # ^^^ ESTO es lo que docker hace con el -p... pero docker la hace en 1 sola máquina
                                # Kubernetes en todas las del cluster
    selector:
        app:            wp     # Pon detras de la IP del servicio en NETFILTER a todos los pods que 
                                    # tengan esta etiqueta en el ns en el que se define este servicio                                    
